### ISSUE TITLE
Android 7.1

### ISSUE THREAD

**Issue by ezjohnson** [bradand/XMouse#18]
Looks like something changed in android 7 or 7.1 that breaks the app. Connecting to host works but commands don't get there.

**Comment by bradand** [comment]
Update: The problem seems to be caused by the "shell" channel intended to be left open during the whole session. As the app runs the initial command with a shell channel, the session breaks immediately. I able to perform normal operations as well as xdotool operations with "exec" channels, but those are opened and closed immediately.

still working...

**Comment by bradand** [comment]
it seems I have found a solution to restore connectivity for Android >6.0:

my answer / addition is in this thread:

http://stackoverflow.com/questions/38144133/android-n-with-jsch-shell-channel-issue/40270446#40270446 

I will publish a new version of the app soon
